blank_issues_enabled: false
contact_links:
  - name: Ask the community for help
    url: https://github.com/dbt-labs/docs.getdbt.com/discussions
    about: Need help troubleshooting? Check out our guide on how to ask
  - name: Contact dbt Cloud support
    url: mailto:support@getdbt.com
    about: Are you using dbt Cloud? Contact our support team for help!
  - name: Participate in Discussions
    url: https://github.com/dbt-labs/dbt-core/discussions
    about: Do you have a Big Idea for dbt? Read open discussions, or start a new one
  - name: Create an issue for dbt-redshift
    url: https://github.com/dbt-labs/dbt-redshift/issues/new/choose
    about: Report a bug or request a feature for dbt-redshift
  - name: Create an issue for dbt-bigquery
    url: https://github.com/dbt-labs/dbt-bigquery/issues/new/choose
    about: Report a bug or request a feature for dbt-bigquery
  - name: Create an issue for dbt-snowflake
    url: https://github.com/dbt-labs/dbt-snowflake/issues/new/choose
    about: Report a bug or request a feature for dbt-snowflake
  - name: Create an issue for dbt-spark
    url: https://github.com/dbt-labs/dbt-spark/issues/new/choose
    about: Report a bug or request a feature for dbt-spark